Circuits v3
0xPolygonID/js-sdk pull request #121
Opened 2023-08-29 14:17 UTC by Kolezhniuk

2023-12-18 14:42 UTC, vmidyllic commented on package.json
> +  "version": "1.4.3",
set new version

2023-12-18 14:44 UTC, vmidyllic commented on src/circuits/atomic-query-sig-v2-on-chain.ts
> +      operator: this.query.operator === Operators.SD ? Operators.EQ : this.query.operator,
same

2023-12-18 14:53 UTC, vmidyllic commented on src/proof/proof-service.ts
> +    const context = proofReq.query['context'] as string;
maybe we can parse proofReq.query to some internal struct ? 
context / type / ...

2023-12-18 14:54 UTC, vmidyllic commented on tests/circuits/utils.ts
> +  const quaryHash = poseidon.hash([
rename typo to queryHash

2023-12-18 14:57 UTC, vmidyllic commented on src/iden3comm/handlers/auth.ts
> +          verifierDid: DID.parse(authRequest.from)
I guess we need to add group id logic here ? because we should generate linkNonce based on group id even for v3 circuit.

2023-12-19 09:50 UTC, volodymyr-basiuk commented on src/proof/common.ts
> +    if (!sigProof.issuerData.mtp) {
maybe move these 2 checks to `!sigProof.issuerData.credentialStatus` check

2023-12-19 09:50 UTC, volodymyr-basiuk commented on src/proof/proof-service.ts
> +      throw new Error('merklized root position is set not set to None for non-merklized schema');
is set not set

2023-12-19 09:50 UTC, volodymyr-basiuk commented on src/storage/filters/jsonQuery.ts
> +      case 'proofType': {
let's group with skipClaimRevocationCheck: 
case 'proofType':
case 'skipClaimRevocationCheck':
  return acc;

2023-12-20 09:05 UTC, volodymyr-basiuk approved these changes

2023-12-20 09:05 UTC, volodymyr-basiuk commented on src/storage/filters/jsonQuery.ts
> +const greaterThanOrEqual = (
could we just return here `!lessThan` ?

2023-12-20 09:05 UTC, volodymyr-basiuk commented on src/storage/filters/jsonQuery.ts
> +const lessThanOrEqual = (
!greaterThan ?

2023-12-20 09:05 UTC, volodymyr-basiuk commented on src/storage/filters/jsonQuery.ts
> +const ninOperator = (
!inOperator ?

2023-12-20 09:05 UTC, volodymyr-basiuk commented on src/storage/filters/jsonQuery.ts
> +    lessThanOrEqual(a, b)
or even here `=> !greaterThan(a, b)`

2023-12-20 09:05 UTC, volodymyr-basiuk commented on src/storage/filters/jsonQuery.ts
> +    ninOperator(a, b),
!inOperator(a, b)

2024-01-04 11:03 UTC, vmidyllic commented on src/circuits/models.ts
> +  AtomicQueryV3 = 'credentialAtomicQueryV3',
change the value of constant AtomicQueryV3  to credentialAtomicQueryV3-beta.0
change the value of constant AtomicQueryV3OnChain  tocredentialAtomicQueryV3OnChain-beta.0 

constant name must remain v3 without beta

2024-01-04 13:27 UTC, vmidyllic approved these changes

2024-01-05 15:36 UTC, vmidyllic requested changes

2024-01-05 15:36 UTC, vmidyllic commented on src/circuits/models.ts
> +  LinkedMultiQuery10 = 'linkedMultiQuery10'
let's also name linkedMultiQuery10-beta.0  , linkedNullifier-beta.0

2024-01-08 07:50 UTC, vmidyllic approved these changes

2024-01-08 07:53 UTC, merged