Add message fetch and issuance message types handling
0xPolygonID/js-sdk pull request #168
Opened 2024-01-22 17:21 UTC by Kolezhniuk

2024-01-23 11:44 UTC, volodymyr-basiuk approved these changes

2024-01-24 08:07 UTC, vmidyllic requested changes

2024-01-24 08:07 UTC, vmidyllic commented on src/iden3comm/handlers/fetch.ts
> +  async handleCredentialFetchRequest(basicMessage: Uint8Array): Promise<Uint8Array> {
it is not a basic message, it can be singed / proven / encrypted envelope (same for issuance)

2024-01-24 08:07 UTC, vmidyllic commented on src/iden3comm/handlers/fetch.ts
> +      throw new Error('invalid claim id in fetch request body');
invalid credential id in fetch request body

2024-01-24 08:07 UTC, vmidyllic commented on src/iden3comm/handlers/fetch.ts
> +      throw new Error('please provide credential wallet in options');
please, provide credential wallet in options

2024-01-24 08:07 UTC, vmidyllic commented on src/iden3comm/handlers/fetch.ts
> +        typ: msgRequest.typ ?? MediaType.PlainMessage,
this is not right, You need to call package manager .pack() with MediaType.PlainMessage

2024-01-24 08:07 UTC, vmidyllic commented on src/iden3comm/handlers/fetch.ts
> +  async handleIssuanceResponseMessage(basicMessage: Uint8Array): Promise<Uint8Array> {
same, rename to envelope (even if it always plain)

2024-01-24 08:07 UTC, vmidyllic commented on src/iden3comm/handlers/fetch.ts
> +      throw new Error('Invalid media type');
it is not a media type, it is message type

2024-01-24 16:24 UTC, vmidyllic approved these changes

2024-01-24 16:25 UTC, merged