move verify pub signals to proof service
0xPolygonID/js-sdk pull request #173
Opened 2024-01-30 11:08 UTC by volodymyr-basiuk

2024-01-31 11:59 UTC, volodymyr-basiuk commented on src/storage/interfaces/resolver.ts
> +// export type StateResolvers = {
Are we sure we don't need StateResolvers (which returns resolver based on DID). I guess we don't need it, but left comment to discuss. @vmidyllic , @Kolezhniuk

2024-02-05 08:17 UTC, vmidyllic requested changes

2024-02-05 08:17 UTC, vmidyllic commented on src/proof/proof-service.ts
> +  ): Promise<BaseConfig>;
let's rename verify to verifyZKPResponse and remove circuitName param, because it is already in proofResp

2024-02-05 09:06 UTC, volodymyr-basiuk commented on src/proof/proof-service.ts
> +  ): Promise<BaseConfig>;
done

2024-02-06 14:34 UTC, merged