update license
0xPolygonID/js-sdk pull request #223
Opened 2024-04-19 09:07 UTC by pragmatos

2024-04-19 19:25 UTC, OBrezhniev approved these changes

2024-04-19 19:29 UTC, OBrezhniev requested changes

2024-04-19 19:29 UTC, OBrezhniev commented on LICENSE-APACHE
> +   Copyright 2023 0kims Association
All 0xPolygonID repos should have (c) ZKID Labs AG, not 0kims Association

2024-04-19 19:29 UTC, OBrezhniev commented on LICENSE-MIT
> +Copyright 2023 0kims Association.
Same here

2024-04-20 08:20 UTC, pragmatos commented on LICENSE-MIT
> +Copyright 2023 0kims Association.
fixed

2024-04-22 13:25 UTC, vmidyllic submitted a review, later dismissed

2024-04-22 13:34 UTC, OBrezhniev commented on LICENSE-APACHE
> +Copyright (C) 2024  ZKID Labs AG
You have copyright at the bottom, why do you need another one at the top?

2024-04-22 13:35 UTC, OBrezhniev commented on LICENSE-APACHE
> +Copyright (C) 2024  ZKID Labs AG
@pragmatos please remove this line.

2024-04-22 14:10 UTC, OBrezhniev approved these changes

2024-04-22 14:14 UTC, vmidyllic approved these changes

2024-04-22 14:14 UTC, merged