WIP: feat: accept header
0xPolygonID/js-sdk pull request #253
Opened 2024-08-09 10:46 UTC by volodymyr-basiuk

2024-08-15 12:11 UTC, vmidyllic requested changes

2024-08-15 12:11 UTC, vmidyllic commented on src/iden3comm/handlers/auth.ts
> +        if (protocolVersion === ProtocolVersion.v1 && responseType.split('/').at(-2) !== '1.0') {
if response type is 1.0 it will not go inside, is it expected?

2024-08-15 12:11 UTC, vmidyllic commented on src/iden3comm/packers/jws.ts
> +  getSupportedAlgorithms(): AcceptJwsAlgorithms[] {
Not sure it is unique

2024-08-27 09:11 UTC, vmidyllic requested changes

2024-08-27 09:11 UTC, vmidyllic commented on src/iden3comm/packers/jws.ts
> +  getEnvelop(): string {
getEnvelope()

2024-08-27 09:11 UTC, vmidyllic commented on src/iden3comm/packers/jws.ts
> +  isSupported(profile: string) {
isProfileSupported

2024-09-09 08:48 UTC, vmidyllic commented on src/iden3comm/handlers/auth.ts
> +        throw new Error('no profile meets `access` header requirements');
throw new Error('no packer with profile which meets `access` header requirements');
Comment

2024-09-09 08:48 UTC, vmidyllic commented on src/iden3comm/packageManager.ts
> +  isSupported(mediaType: MediaType, profile: string): boolean {
you should rename interface method to` isProfileSupported` too

2024-09-09 08:48 UTC, vmidyllic commented on src/iden3comm/packers/zkp.ts
> +  getEnvelope(): string {
and in future I guess we will have potentially an array of strings even for one media type, maybe we should return an array of strings and rename methods to getAcceptedProfiles()

2024-09-30 09:15 UTC, vmidyllic submitted a review, later dismissed

2024-11-19 16:15 UTC, Kolezhniuk commented on src/iden3comm/constants.ts
> +  v1 = 'iden3comm/v1'
I guess names for enum should be PascalCase

2024-11-19 16:29 UTC, Kolezhniuk commented on src/iden3comm/utils/accept-profile.ts
> +        .map((i) => i.trim())
I believe you could call trim in one map, to avoid additional iteration

2024-11-19 16:30 UTC, Kolezhniuk commented on src/iden3comm/utils/accept-profile.ts
> +        .map((i) => i.trim())
same here

2024-11-20 04:47 UTC, Kolezhniuk approved these changes

2024-11-21 14:47 UTC, vmidyllic submitted a review, later dismissed

2024-11-21 15:12 UTC, vmidyllic approved these changes

2024-11-21 15:20 UTC, Kolezhniuk approved these changes

2024-11-21 15:22 UTC, merged