Feature/pid-381
0xPolygonID/js-sdk pull request #59
Opened 2023-04-10 17:35 UTC by Kolezhniuk

2023-04-11 10:47 UTC, vmidyllic requested changes

2023-04-11 10:47 UTC, vmidyllic commented on src/credentials/credential-wallet.ts
> +        ? `${request.revocationOpts.baseUrl}/revocation/${request.revocationOpts.nonce}`
? `${request.revocationOpts.baseUrl}/${request.revocationOpts.nonce}` :

2023-04-11 10:47 UTC, vmidyllic commented on src/identity/identity-wallet.ts
> +  createIdentity(opts?: IdentityCreationOptions): Promise<{ did: DID; credential: W3CCredential }>;
here it's optional, in the implementation it's not

2023-04-11 16:48 UTC, Kolezhniuk commented
@vmidyllic fixed your comments

2023-04-14 13:57 UTC, merged

2023-04-17 21:18 UTC, nedgar commented on index.html
> +                baseUrl: 'http://rhs.com/node'
rhs.com is an in-use domain. Suggest using the actual Polygon ID RHS.